name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '2.1' # version od .net core sdk to use
    - name: dotnet build
      run: dotnet build PackageA.sln

